<table class="table table-striped">
    <thead>
        <tr>
            <?php foreach($dataHelper->getColumns() as $column) : ?>
                <th><?php echo $column->getLabel(); ?></th>
            <?php endforeach; ?>
            <?php if($dataHelper->hasActionColumn()) : ?>
                <th><?php echo $this->translate('datatable.actions'); ?></th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($rows as $row) : ?>
            <tr>
                <?php foreach($dataHelper->getColumns() as $column) : ?>
                    <?php $method = 'get' . ucfirst($column->getIndex()); ?>
                    <td>
                        <?php $val = $column($row->$method()); ?>
                        <?php echo $val ? $this->translate($val)  : ''; ?>
                    </td>
                <?php endforeach; ?>
                <?php if($dataHelper->hasActionColumn()) : ?>
                    <td>
                        <div class="btn-group">
                            <?php foreach($dataHelper->getCustomActions() as $action) : ?>
                                <?php /* @var $action \MwAdmin\View\Helper\DataTable\ActionInterface */?>
                                <a target="<?php echo $action->getTarget(); ?>" class="btn btn-default" href="<?php echo $dataHelper->getCustomLink($action, $row); ?>">
                                    <?php echo $this->translate($action->getLabel()); ?>
                                </a>
                            <?php endforeach; ?>
                            <?php if($dataHelper->hasReadLink()) : ?>
                                <a target="<?php echo $dataHelper->getReadTarget(); ?>" class="btn btn-default" href="<?php echo $dataHelper->getReadLink($row); ?>">
                                    <?php echo $this->translate('datatable.view'); ?>
                                </a>
                            <?php endif; ?>
                            <?php if($dataHelper->hasEditLink()) : ?>
                                <a class="btn btn-default" href="<?php echo $dataHelper->getEditLink($row); ?>">
                                    <?php echo $this->translate('datatable.edit'); ?>
                                </a>
                            <?php endif; ?>
                            <?php if($dataHelper->hasDeleteLink()) : ?>
                                <a class="btn btn-danger" href="<?php echo $dataHelper->getDeleteLink($row); ?>">
                                    <?php echo $this->translate('datatable.delete'); ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="99">
                <?php echo $this->paginationcontrol($rows, null, 'mwadmin/pagination'); ?>
            </td>
        </tr>
    </tfoot>
</table>