<table class="table table-striped">
    <thead>
        <tr>
            <?php foreach($dataHelper->getColumns() as $col => $label) : ?>
                <th><?php echo $label; ?></th>
            <?php endforeach; ?>
            <?php if($dataHelper->hasActionColumn()) : ?>
                <th>Actions</th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($rows as $row) : ?>
            <tr>
                <?php foreach($dataHelper->getColumns() as $col => $label) : ?>
                    <?php $method = 'get' . ucfirst($col); ?>
                    <td>
                        <?php echo $this->valueFormat($row->$method()); ?>
                    </td>
                <?php endforeach; ?>
                <?php if($dataHelper->hasActionColumn()) : ?>
                    <td>
                        <div class="btn-group">
                            <?php if($dataHelper->hasReadLink()) : ?>
                                <a target="<?php echo $dataHelper->getReadTarget(); ?>" class="btn btn-default" href="<?php echo $dataHelper->getReadLink($row); ?>">View</a>
                            <?php endif; ?>
                            <?php if($dataHelper->hasEditLink()) : ?>
                                <a class="btn btn-default" href="<?php echo $dataHelper->getEditLink($row); ?>">Edit</a>
                            <?php endif; ?>
                            <?php if($dataHelper->hasDeleteLink()) : ?>
                                <a class="btn btn-danger" href="<?php echo $dataHelper->getDeleteLink($row); ?>">Delete</a>
                            <?php endif; ?>
                        </div>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="99">footer</td>
        </tr>
    </tfoot>
</table>