<?php if ($this->pageCount): ?>
<ul class="pagination">
    <?php if (isset($this->previous)): ?>
        <li><a href="<?php echo $this->url(); ?>?page=<?php echo $this->previous; ?>">&laquo;</a></li>
    <?php endif; ?>
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li><a href="<?php echo $this->url(); ?>?page=<?php echo $page; ?>"><?php echo $page; ?></a></li>
        <?php else: ?>
            <li class="active"><span><?php echo $page; ?></span></li>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if (isset($this->next)): ?>
        <li><a href="<?php echo $this->url(); ?>?page=<?php echo $this->next ?>">&raquo;</a></li>
    <?php endif; ?>
</ul>
<?php endif; ?>