<?php echo $this->doctype(); ?>

<html lang="de">
<head>
<meta charset="utf-8">
    <?php echo $this->headTitle('ZfcAdmin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false)?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
    
    <?php echo $this->bootstrapCss(); ?>
    <?php echo $this->bootstrapJs()->prependFile($this->basePath('js/jquery-2.0.3.min.js')); ?>
  </head>

<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('zfcadmin'); ?>">
                <?php echo $this->mwAdminBrandName(); ?>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <?php if($this->zfcUserIdentity()) : ?>
                <ul class="nav navbar-nav">
                <?php echo $this->navigation('admin_navigation')
                    ->menu()
                    ->setPartial('layout/bootstrap-menu.phtml')
                ?>
                </ul>
                <p class="navbar-text navbar-right">
                    <?php echo sprintf($this->translate('menu.welcome'), $this->zfcUserDisplayName()) ?></strong>
                    <a class="navbar-link" href="<?php echo $this->url('zfcuser/logout'); ?>">
                        <?php echo $this->translate('menu.logout'); ?>
                    </a>
                </p>
            <?php endif; ?>
        </div>
    </nav>
    <div class="container">
        <?php echo $this->content; ?>
        <hr>
        <footer>
            <p>&copy; <?php echo date('Y'); ?> mehrWEB - Agentur für Neue Medien.</p>
        </footer>
    </div>
    <?php echo $this->inlineScript() ?>
</body>
</html>